FROM node:latest

# Create an application directory
RUN mkdir -p /server

RUN apt-get update || : && apt-get install python -y
RUN apt install python3-pip -y
RUN pip install requests numpy pandas geopandas
# The /server directory should act as the main serverlication directory
WORKDIR /server

# Copy the server package and package-lock.json file
COPY server/ ./

# Install node packages
RUN npm install


# Expose $PORT on container.
# We use a varibale here as the port is something that can differ on the environment.
ENV PORT 5001

# Set host to localhost / the docker image
ENV NUXT_HOST=0.0.0.0

# Set app port
ENV NUXT_PORT=PORT

# Start the app
CMD [ "node", "app.js" ]

