FROM python:3

ADD twitter_streaming.py stem_keywords.py fetch_coordinates.py /src/
ADD res /src/res/

ENV BEARER_TOKEN None
ENV COUCHDB_USERNAME admin  
ENV COUCHDB_PASSWORD admin

ENV KEYWORDS None
ENV BOUNDING_BOX "143.7832,-38.5375,146.1406,-37.0837"

RUN pip install --user -U nltk
RUN pip install python-dotenv CouchDB requests shapely
RUN pip install numpy pandas geopandas
RUN ls -la /src/res


CMD [ "python", "./src/twitter_streaming.py" ]
